### ISSUE TITLE
Steam Deck Support

### ISSUE THREAD

**Issue by chyyran** [chyyran/skyinstaller#1]
SkyInstaller currently only supports Windows because of Steam requirements. Once I get a Steam Deck, should look into supporting one-click installs of the Evolution voices on Linux.

**Comment by chyyran** [comment]
[avalonia-new-picker](https://github.com/chyyran/skyinstaller/tree/avalonia-new-picker) is fully cross-platform but is blocking on Avalonia 11.

**Comment by chyyran** [comment]
also need a vdf reader before publishing this to add `WINEDLLOVERRIDES="dinput8=n,b" %command%`

**Comment by chyyran** [comment]
steam deck in hand but aui11 is still mia

**Comment by chyyran** [comment]
https://github.com/chyyran/skyinstaller/commit/26b64e93688df72014ad26f4915fc59052f580b3 inplements steam deck support, rest is packaging ( Flatpak)

**Comment by cprivitere** [comment]
Just wanted to confirm for you that the current 1.4.1 beta worked great on my Steamdeck.
